In [1]:
from utils.utils import TransformRawData

In [4]:
analysis_name = "exploration"

In [5]:
instance = TransformRawData(analysis_name)

In [6]:
instance.create_df_all()

In [7]:
instance.df_all

,brand_id,car_id,car_component,component_id,timestamp,component_part_id,sensor_1,sensor_2,sensor_3,sensor_4,non_defect_likelihood
0,7623909,234444,motor,8285,2022-05-25 21:09:54.672448,44,1.006716,18089.04,128.66488,18083.80,0.999877
1,7623909,234444,motor,8285,2022-05-25 21:09:54.672448,32,1.098652,10797.78,133.19207,19093.06,0.999835
2,7623909,234444,motor,8285,2022-05-25 21:09:54.672448,31,0.976108,13513.02,109.99874,20455.96,0.999850
3,7623909,234444,motor,8285,2022-05-25 21:09:54.672448,34,1.148134,18603.00,107.10599,24748.64,0.999865
4,7623909,234444,motor,8285,2022-05-25 21:09:54.672448,22,0.649694,10917.00,91.81226,16296.28,0.999873
...,...,...,...,...,...,...,...,...,...,...,...
2238946,7623909,234579,motor,8977,2023-05-03 21:29:31.951756,11,1.401136,31534.72,93.75132,19967.25,0.999868
2238947,7623909,234579,motor,8977,2023-05-03 21:29:31.951756,12,1.040714,24136.64,98.85096,14097.87,0.999895
2238948,7623909,234579,motor,8977,2023-05-03 21:29:31.951756,33,2.277857,41336.32,104.74516,29016.45,0.999850
2238949,7623909,234579,motor,8977,2023-05-03 21:29:31.951756,34,2.055146,42747.36,97.22882,28152.30,0.999853
2238950,7623909,234579,motor,8977,2023-05-03 21:29:31.951756,41,2.122574,48910.72,117.91130,24043.35,0.999853